export const singleJobData = {
  logo: "/images/sample_logo.png",
  companyName: "Company",
  position: "Position",
  primaryTag: "Full stack",
  tags: ["ruby", "rails", "ecommerce"],
  location: "Worldwide",
  minSalary: 50000,
  maxSalary: 80000,
  howtoApply:
    "Visit our [careers site](https://join.nadinewest.com/) to upload your resume. If your work experience suggests a potential match, you'll be invited to take a 10-hour, fully-paid [coding challenge](https://join.nadinewest.com/coding-challenge/). Top performers in the coding challenge will be invited to interview with the CEO and the tech leads.",

  isShowLogo: true,
  isHighlight: false,
  //   isHighlightColor: false,
  isStickyDay: false,
  //   isStickyWeek: false,
  isStickyMonth: true,
  postedAt: "2021-06-10 11:59:59",
  createdAt: "2020-06-10 17:59:59",
};

export const jobsData = [
  {
    logo: "/images/sample_logo.png",
    companyName: "Grafana",
    position: "Documentation & Technical Writing Manager",
    primaryTag: "Technical writing",
    tags: ["writing", "documentation", "exec"],
    location: "Worldwide",
    minSalary: 50000,
    maxSalary: 80000,
    howtoApply:
      "Visit our [careers site](https://join.nadinewest.com/) to upload your resume. If your work experience suggests a potential match, you'll be invited to take a 10-hour, fully-paid [coding challenge](https://join.nadinewest.com/coding-challenge/). Top performers in the coding challenge will be invited to interview with the CEO and the tech leads.",

    isShowLogo: true,
    isHighlight: true,
    //   isHighlightColor: false,
    isStickyDay: false,
    //   isStickyWeek: false,
    isStickyMonth: true,
    postedAt: "2021-06-10 11:59:59",
    createdAt: "2020-06-10 17:59:59",
  },
  {
    logo: "/images/sample_logo.png",
    companyName: "Nadine West",
    position: "Position",
    primaryTag: "Full stack",
    tags: ["ruby", "rails", "ecommerce"],
    location: "Worldwide",
    minSalary: 50000,
    maxSalary: 80000,
    howtoApply:
      "Visit our [careers site](https://join.nadinewest.com/) to upload your resume. If your work experience suggests a potential match, you'll be invited to take a 10-hour, fully-paid [coding challenge](https://join.nadinewest.com/coding-challenge/). Top performers in the coding challenge will be invited to interview with the CEO and the tech leads.",

    isShowLogo: true,
    // isHighlight: false,
    isHighlightColor: true,
    highlightColor: "#ff00a2",
    isStickyDay: false,
    isStickyWeek: true,
    // isStickyMonth: true,
    postedAt: "2021-06-10 11:59:59",
    createdAt: "2020-06-10 17:59:59",
  },
  {
    logo: "/images/sample_logo.png",
    companyName: "Aliens.com",
    position: "Position",
    primaryTag: "exec",
    tags: ["tech lead", "mobile", "full stack"],
    location: "Worldwide",
    minSalary: 50000,
    maxSalary: 80000,
    howtoApply:
      "Visit our [careers site](https://join.nadinewest.com/) to upload your resume. If your work experience suggests a potential match, you'll be invited to take a 10-hour, fully-paid [coding challenge](https://join.nadinewest.com/coding-challenge/). Top performers in the coding challenge will be invited to interview with the CEO and the tech leads.",
    isShowLogo: true,
    isHighlight: false,
    //   isHighlightColor: false,
    isStickyDay: false,
    //   isStickyWeek: false,
    isStickyMonth: true,
    postedAt: "2021-06-10 11:59:59",
    createdAt: "2020-06-10 17:59:59",
  },
];
